/**
 * NOTE: This class is auto generated by the swagger code generator program (2.3.1).
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */
package io.swagger.api;

import io.swagger.model.Category;
import io.swagger.annotations.*;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

import javax.validation.Valid;

@javax.annotation.Generated(value = "io.swagger.codegen.languages.SpringCodegen", date = "2018-08-01T20:29:30.132Z")

@Api(value = "category", description = "the category API")
public interface CategoryApi {

    @ApiOperation(value = "Add a new category", nickname = "addcategory", notes = "", tags={ "category", })
    @ApiResponses(value = { 
        @ApiResponse(code = 405, message = "Invalid input") })
    @RequestMapping(value = "/category",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.POST)
    ResponseEntity<Void> addcategory(@ApiParam(value = "category object that needs to be added" ,required=true )  @Valid @RequestBody Category body);


    @ApiOperation(value = "delete an existing category", nickname = "deletecategory", notes = "", tags={ "category", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Category not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/category",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.DELETE)
    ResponseEntity<Void> deletecategory(@ApiParam(value = "category object that needs to be deleted" ,required=true )  @Valid @RequestBody Category body);


    @ApiOperation(value = "Update an existing category", nickname = "updatecategory", notes = "", tags={ "category", })
    @ApiResponses(value = { 
        @ApiResponse(code = 400, message = "Invalid ID supplied"),
        @ApiResponse(code = 404, message = "Category not found"),
        @ApiResponse(code = 405, message = "Validation exception") })
    @RequestMapping(value = "/category",
        produces = { "application/xml", "application/json" }, 
        consumes = { "application/json", "application/xml" },
        method = RequestMethod.PUT)
    ResponseEntity<Void> updatecategory(@ApiParam(value = "Category object that needs to be added" ,required=true )  @Valid @RequestBody Category body);

}
